# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: ae6df872-656e-4cb4-962b-0709bdef510b
version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: Collect Test Reports
          command: |
            echo a > ./rspec.xml
            mkdir -p ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/ae6df872-656e-4cb4-962b-0709bdef510b/0
            cp ./rspec.xml ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/ae6df872-656e-4cb4-962b-0709bdef510b/0
      - store_artifacts:
          path: ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/ae6df872-656e-4cb4-962b-0709bdef510b/0

workflows:
  version: 2
  main:
    jobs:
      - store-old
