version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Collect Test Reports
          command: |
            mkdir -p ../test-reports/server/
            cp ./rspec.xml ../test-reports/server/
      - store_test_results:
          path: ../test-results
      - store_artifacts:
          path: ../test-results

workflows:
  version: 2
  main:
    jobs:
      - store-old
