version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    parallelism: 10
    steps:
      - run:
          name: do it
          command: |
            echo aaaaaaaa > a
      - save_cache:
          paths:
            - ./a
          key: a-key

workflows:
  version: 2
  main:
    jobs:
      - store-old
