version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: minio/minio
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'
    steps:
      - run:
          name: do it
          command: |
            minio server --address :9123 /data

workflows:
  version: 2
  main:
    jobs:
      - store-old
