# project id: 96809a41-b0ec-48af-bff6-8b6feea449d4
# job id: b2cb2653-cc4d-412c-ac74-70873bb302aa
version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: Collect Test Reports
          command: |
            echo a > ./rspec.xml
            mkdir -p ../../../../96809a41-b0ec-48af-bff6-8b6feea449d4/b2cb2653-cc4d-412c-ac74-70873bb302aa/0
            cp ./rspec.xml ../../../../96809a41-b0ec-48af-bff6-8b6feea449d4/b2cb2653-cc4d-412c-ac74-70873bb302aa/0
      - store_artifacts:
          path: ../../../../96809a41-b0ec-48af-bff6-8b6feea449d4/b2cb2653-cc4d-412c-ac74-70873bb302aa/0

workflows:
  version: 2
  main:
    jobs:
      - store-old
