version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: make file
          command: |
            mkdir -p /tmp/ws
            echo old > /tmp/ws/old
      - persist_to_workspace:
          root: /tmp/ws
          paths:
            - old
  store-new:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: make file
          command: |
            mkdir -p /tmp/ws
            echo new > /tmp/ws/new
      - persist_to_workspace:
          root: /tmp/ws
          paths:
            - new
  restore:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - attach_workspace:
          at: /tmp/ws
      - run:
          name: assert ws
          command: |
            cat /tmp/ws/old
            cat /tmp/ws/new

workflow:
  main:
    jobs:
      - store-old
      - hold:
          type: approval
      - store-new
      - restore
