# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2.1'

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: mat1g3r/deck
    steps:
      - run: neofetch
