version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - store_test_results:
          path: .
      - store_artifacts:
          path: .

workflows:
  version: 2
  main:
    jobs:
      - store-old
