version: '2.1'

jobs:
  tests:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: generate garbage test results
          command: |
            echo hi > a.xml
      - store_test_results:
          path: large.xml.0

workflows:
  the_workflow:
    jobs:
      - tests
