# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2'

jobs:
  store-old:
    parallel: 2
    resource_class: small
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: |
          python ./test-results/a.py > ./test-results/1.xml
          python ./test-results/a.py > ./test-results/2.xml
          python ./test-results/a.py > ./test-results/3.xml
          python ./test-results/a.py > ./test-results/4.xml
          python ./test-results/a.py > ./test-results/5.xml
          python ./test-results/a.py > ./test-results/6.xml
          python ./test-results/a.py > ./test-results/7.xml
          python ./test-results/a.py > ./test-results/8.xml
          python ./test-results/a.py > ./test-results/9.xml
          python ./test-results/a.py > ./test-results/10.xml
          python ./test-results/a.py > ./test-results/11.xml
          python ./test-results/a.py > ./test-results/12.xml
          python ./test-results/a.py > ./test-results/13.xml
          python ./test-results/a.py > ./test-results/14.xml
          python ./test-results/a.py > ./test-results/15.xml
      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  main:
    jobs:
      - store-old
