# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2.1'

jobs:
  build:
    resource_class: small
    docker:
      - image: moby/buildkit:master
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=. --local dockerfile=.

workflows:
  version: 2
  main:
    jobs:
      - build
