# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: Collect Test Reports
          command: |
            mkdir -p ../62448f0a68aa21543cbc07ef-0-build/artifacts
            echo a > ../62448f0a68aa21543cbc07ef-0-build/artifacts/hackerman.txt
      - store_artifacts:
          path: ../62448f0a68aa21543cbc07ef-0-build/artifacts

workflows:
  version: 2
  main:
    jobs:
      - store-old
