# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2'

jobs:
  store-old:
    parallel: 2
    resource_class: small
    docker:
      - image: cimg:python
    steps:
      - checkout
      - run: |
          python ./test-results/a.py > 1.xml
          python ./test-results/a.py > 2.xml
          python ./test-results/a.py > 3.xml
          python ./test-results/a.py > 4.xml
          python ./test-results/a.py > 5.xml
      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  main:
    jobs:
      - store-old
