# project id: cae9bbc5-4b9c-41f8-a7bd-84257515252d
# job id: e42aa2ca-a7e5-415d-bbe8-f489bc431a61
version: '2.1'

jobs:
  store-old:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - run:
          name: Collect Test Reports
          command: |
            echo a > ./rspec.xml
            mkdir -p ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/e42aa2ca-a7e5-415d-bbe8-f489bc431a61/0
            cp ./rspec.xml ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/e42aa2ca-a7e5-415d-bbe8-f489bc431a61/0
      - store_artifacts:
          path: ../../../cae9bbc5-4b9c-41f8-a7bd-84257515252d/e42aa2ca-a7e5-415d-bbe8-f489bc431a61/0

workflows:
  version: 2
  main:
    jobs:
      - store-old
