version: '2.1'

jobs:
  tests:
    resource_class: small
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: make workspace
          command: |
            mkdir -p /tmp/dir2/foo
            echo aaaaaa > /tmp/dir2/foo/a
            echo bbbbbb > /tmp/dir2/foo/b
      - persist_to_workspace:
          root: /tmp/dir2
          paths:
            - foo
      - attach_workspace:
          at: /tmp/dir2
      - restore_cache:
          keys:
            - rspec
      - save_cache:
          key: rspec-3
          paths:
            - rspec.xml
      - store_test_results:
          path: rspec.xml
      - store_artifacts:
          path: rspec.xml
workflows:
  the_workflow:
    jobs:
      - tests
